# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dndml/enums/enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64ndml/enums/enums.proto\x12\x0b\x64ndml.enums*W\n\x06Object\x12\x14\n\x10undefined_object\x10\x00\x12\n\n\x06\x61\x63tion\x10\x01\x12\x0c\n\x08\x63reature\x10\x02\x12\x08\n\x04\x66\x65\x61t\x10\x03\x12\x08\n\x04item\x10\x04\x12\t\n\x05trait\x10\x05*\x98\x01\n\x05\x43lass\x12\x13\n\x0fundefined_class\x10\x00\x12\r\n\tbarbarian\x10\x01\x12\x08\n\x04\x62\x61rd\x10\x02\x12\n\n\x06\x63leric\x10\x03\x12\x0b\n\x07\x66ighter\x10\x04\x12\x08\n\x04monk\x10\x05\x12\x0b\n\x07paladin\x10\x06\x12\n\n\x06ranger\x10\x07\x12\x0c\n\x08sorcerer\x10\x08\x12\x0b\n\x07warlock\x10\t\x12\n\n\x06wizard\x10\n*Q\n\x06Period\x12\x14\n\x10undefined_period\x10\x00\x12\t\n\x05round\x10\x01\x12\x0e\n\nshort_rest\x10\x02\x12\r\n\tlong_rest\x10\x03\x12\x07\n\x03\x64\x61y\x10\x04\x42\x30Z.github.com/theaufish-git/dndml/pkg/dndml/enumsb\x06proto3')

_OBJECT = DESCRIPTOR.enum_types_by_name['Object']
Object = enum_type_wrapper.EnumTypeWrapper(_OBJECT)
_CLASS = DESCRIPTOR.enum_types_by_name['Class']
Class = enum_type_wrapper.EnumTypeWrapper(_CLASS)
_PERIOD = DESCRIPTOR.enum_types_by_name['Period']
Period = enum_type_wrapper.EnumTypeWrapper(_PERIOD)
undefined_object = 0
action = 1
creature = 2
feat = 3
item = 4
trait = 5
undefined_class = 0
barbarian = 1
bard = 2
cleric = 3
fighter = 4
monk = 5
paladin = 6
ranger = 7
sorcerer = 8
warlock = 9
wizard = 10
undefined_period = 0
round = 1
short_rest = 2
long_rest = 3
day = 4


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/theaufish-git/dndml/pkg/dndml/enums'
  _OBJECT._serialized_start=40
  _OBJECT._serialized_end=127
  _CLASS._serialized_start=130
  _CLASS._serialized_end=282
  _PERIOD._serialized_start=284
  _PERIOD._serialized_end=365
# @@protoc_insertion_point(module_scope)
