# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dndml/v5/stats.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dndml import roll_pb2 as dndml_dot_roll__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64ndml/v5/stats.proto\x12\x08\x64ndml.v5\x1a\x10\x64ndml/roll.proto\"[\n\x06Health\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\r\x12\x0f\n\x07maximum\x18\x02 \x01(\r\x12\x11\n\ttemporary\x18\x03 \x01(\r\x12\x1c\n\x07\x61verage\x18\x04 \x01(\x0b\x32\x0b.dndml.Roll\"?\n\x04Stat\x12\x0c\n\x04stat\x18\x01 \x01(\x05\x12)\n\tmodifiers\x18\x02 \x03(\x0b\x32\x16.dndml.v5.StatModifier\"+\n\x0cStatModifier\x12\x0c\n\x04\x64\x65sc\x18\x01 \x01(\t\x12\r\n\x05\x62onus\x18\x02 \x01(\x05\"\xb5\x01\n\x05Stats\x12\x1b\n\x03str\x18\x02 \x01(\x0b\x32\x0e.dndml.v5.Stat\x12\x1b\n\x03\x64\x65x\x18\x03 \x01(\x0b\x32\x0e.dndml.v5.Stat\x12\x1b\n\x03\x63on\x18\x04 \x01(\x0b\x32\x0e.dndml.v5.Stat\x12\x1b\n\x03int\x18\x05 \x01(\x0b\x32\x0e.dndml.v5.Stat\x12\x1b\n\x03wis\x18\x06 \x01(\x0b\x32\x0e.dndml.v5.Stat\x12\x1b\n\x03\x63ha\x18\x07 \x01(\x0b\x32\x0e.dndml.v5.Stat\"\xa1\x01\n\nSpellSlots\x12\x0c\n\x04\x64\x65sc\x18\x01 \x01(\t\x12\r\n\x05lvl_1\x18\x02 \x01(\x05\x12\r\n\x05lvl_2\x18\x03 \x01(\x05\x12\r\n\x05lvl_3\x18\x04 \x01(\x05\x12\r\n\x05lvl_4\x18\x05 \x01(\x05\x12\r\n\x05lvl_5\x18\x06 \x01(\x05\x12\r\n\x05lvl_6\x18\x07 \x01(\x05\x12\r\n\x05lvl_7\x18\x08 \x01(\x05\x12\r\n\x05lvl_8\x18\t \x01(\x05\x12\r\n\x05lvl_9\x18\n \x01(\x05\x42-Z+github.com/theaufish-git/dndml/pkg/dndml/v5b\x06proto3')



_HEALTH = DESCRIPTOR.message_types_by_name['Health']
_STAT = DESCRIPTOR.message_types_by_name['Stat']
_STATMODIFIER = DESCRIPTOR.message_types_by_name['StatModifier']
_STATS = DESCRIPTOR.message_types_by_name['Stats']
_SPELLSLOTS = DESCRIPTOR.message_types_by_name['SpellSlots']
Health = _reflection.GeneratedProtocolMessageType('Health', (_message.Message,), {
  'DESCRIPTOR' : _HEALTH,
  '__module__' : 'dndml.v5.stats_pb2'
  # @@protoc_insertion_point(class_scope:dndml.v5.Health)
  })
_sym_db.RegisterMessage(Health)

Stat = _reflection.GeneratedProtocolMessageType('Stat', (_message.Message,), {
  'DESCRIPTOR' : _STAT,
  '__module__' : 'dndml.v5.stats_pb2'
  # @@protoc_insertion_point(class_scope:dndml.v5.Stat)
  })
_sym_db.RegisterMessage(Stat)

StatModifier = _reflection.GeneratedProtocolMessageType('StatModifier', (_message.Message,), {
  'DESCRIPTOR' : _STATMODIFIER,
  '__module__' : 'dndml.v5.stats_pb2'
  # @@protoc_insertion_point(class_scope:dndml.v5.StatModifier)
  })
_sym_db.RegisterMessage(StatModifier)

Stats = _reflection.GeneratedProtocolMessageType('Stats', (_message.Message,), {
  'DESCRIPTOR' : _STATS,
  '__module__' : 'dndml.v5.stats_pb2'
  # @@protoc_insertion_point(class_scope:dndml.v5.Stats)
  })
_sym_db.RegisterMessage(Stats)

SpellSlots = _reflection.GeneratedProtocolMessageType('SpellSlots', (_message.Message,), {
  'DESCRIPTOR' : _SPELLSLOTS,
  '__module__' : 'dndml.v5.stats_pb2'
  # @@protoc_insertion_point(class_scope:dndml.v5.SpellSlots)
  })
_sym_db.RegisterMessage(SpellSlots)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/theaufish-git/dndml/pkg/dndml/v5'
  _HEALTH._serialized_start=52
  _HEALTH._serialized_end=143
  _STAT._serialized_start=145
  _STAT._serialized_end=208
  _STATMODIFIER._serialized_start=210
  _STATMODIFIER._serialized_end=253
  _STATS._serialized_start=256
  _STATS._serialized_end=437
  _SPELLSLOTS._serialized_start=440
  _SPELLSLOTS._serialized_end=601
# @@protoc_insertion_point(module_scope)
