# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dndml/v5/trait.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dndml.v5 import uses_pb2 as dndml_dot_v5_dot_uses__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64ndml/v5/trait.proto\x12\x08\x64ndml.v5\x1a\x13\x64ndml/v5/uses.proto\"\x9a\x01\n\x05Trait\x12\x13\n\x06source\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08template\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x0c\n\x04kind\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x1c\n\x04uses\x18\x06 \x01(\x0b\x32\x0e.dndml.v5.UsesB\t\n\x07_sourceB\x0b\n\t_templateB-Z+github.com/theaufish-git/dndml/pkg/dndml/v5b\x06proto3')



_TRAIT = DESCRIPTOR.message_types_by_name['Trait']
Trait = _reflection.GeneratedProtocolMessageType('Trait', (_message.Message,), {
  'DESCRIPTOR' : _TRAIT,
  '__module__' : 'dndml.v5.trait_pb2'
  # @@protoc_insertion_point(class_scope:dndml.v5.Trait)
  })
_sym_db.RegisterMessage(Trait)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/theaufish-git/dndml/pkg/dndml/v5'
  _TRAIT._serialized_start=56
  _TRAIT._serialized_end=210
# @@protoc_insertion_point(module_scope)
