// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: dndml/v5/trait.proto

package v5

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trait struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source      *string `protobuf:"bytes,1,opt,name=source,proto3,oneof" json:"source,omitempty"`
	Template    *string `protobuf:"bytes,2,opt,name=template,proto3,oneof" json:"template,omitempty"`
	Kind        string  `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Name        string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Uses        *Uses   `protobuf:"bytes,6,opt,name=uses,proto3" json:"uses,omitempty"`
}

func (x *Trait) Reset() {
	*x = Trait{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dndml_v5_trait_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trait) ProtoMessage() {}

func (x *Trait) ProtoReflect() protoreflect.Message {
	mi := &file_dndml_v5_trait_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trait.ProtoReflect.Descriptor instead.
func (*Trait) Descriptor() ([]byte, []int) {
	return file_dndml_v5_trait_proto_rawDescGZIP(), []int{0}
}

func (x *Trait) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *Trait) GetTemplate() string {
	if x != nil && x.Template != nil {
		return *x.Template
	}
	return ""
}

func (x *Trait) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Trait) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Trait) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Trait) GetUses() *Uses {
	if x != nil {
		return x.Uses
	}
	return nil
}

var File_dndml_v5_trait_proto protoreflect.FileDescriptor

var file_dndml_v5_trait_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x76, 0x35, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2e, 0x76, 0x35,
	0x1a, 0x13, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x76, 0x35, 0x2f, 0x75, 0x73, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcb, 0x01, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x69, 0x74, 0x12,
	0x1b, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2e, 0x76, 0x35,
	0x2e, 0x55, 0x73, 0x65, 0x73, 0x52, 0x04, 0x75, 0x73, 0x65, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x68, 0x65, 0x61, 0x75, 0x66, 0x69, 0x73, 0x68, 0x2d, 0x67, 0x69, 0x74, 0x2f,
	0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f,
	0x76, 0x35, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dndml_v5_trait_proto_rawDescOnce sync.Once
	file_dndml_v5_trait_proto_rawDescData = file_dndml_v5_trait_proto_rawDesc
)

func file_dndml_v5_trait_proto_rawDescGZIP() []byte {
	file_dndml_v5_trait_proto_rawDescOnce.Do(func() {
		file_dndml_v5_trait_proto_rawDescData = protoimpl.X.CompressGZIP(file_dndml_v5_trait_proto_rawDescData)
	})
	return file_dndml_v5_trait_proto_rawDescData
}

var file_dndml_v5_trait_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dndml_v5_trait_proto_goTypes = []interface{}{
	(*Trait)(nil), // 0: dndml.v5.Trait
	(*Uses)(nil),  // 1: dndml.v5.Uses
}
var file_dndml_v5_trait_proto_depIdxs = []int32{
	1, // 0: dndml.v5.Trait.uses:type_name -> dndml.v5.Uses
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dndml_v5_trait_proto_init() }
func file_dndml_v5_trait_proto_init() {
	if File_dndml_v5_trait_proto != nil {
		return
	}
	file_dndml_v5_uses_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dndml_v5_trait_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trait); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dndml_v5_trait_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dndml_v5_trait_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dndml_v5_trait_proto_goTypes,
		DependencyIndexes: file_dndml_v5_trait_proto_depIdxs,
		MessageInfos:      file_dndml_v5_trait_proto_msgTypes,
	}.Build()
	File_dndml_v5_trait_proto = out.File
	file_dndml_v5_trait_proto_rawDesc = nil
	file_dndml_v5_trait_proto_goTypes = nil
	file_dndml_v5_trait_proto_depIdxs = nil
}
