// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: dndml/v5/uses.proto

package v5

import (
	dndml "github.com/theaufish-git/dndml/pkg/dndml"
	enums "github.com/theaufish-git/dndml/pkg/dndml/v5/enums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Uses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count    int32        `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Period   enums.Period `protobuf:"varint,2,opt,name=period,proto3,enum=dndml.v5.enums.Period" json:"period,omitempty"`
	Recharge *dndml.Roll  `protobuf:"bytes,3,opt,name=recharge,proto3" json:"recharge,omitempty"`
}

func (x *Uses) Reset() {
	*x = Uses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dndml_v5_uses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uses) ProtoMessage() {}

func (x *Uses) ProtoReflect() protoreflect.Message {
	mi := &file_dndml_v5_uses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uses.ProtoReflect.Descriptor instead.
func (*Uses) Descriptor() ([]byte, []int) {
	return file_dndml_v5_uses_proto_rawDescGZIP(), []int{0}
}

func (x *Uses) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Uses) GetPeriod() enums.Period {
	if x != nil {
		return x.Period
	}
	return enums.Period(0)
}

func (x *Uses) GetRecharge() *dndml.Roll {
	if x != nil {
		return x.Recharge
	}
	return nil
}

var File_dndml_v5_uses_proto protoreflect.FileDescriptor

var file_dndml_v5_uses_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x76, 0x35, 0x2f, 0x75, 0x73, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2e, 0x76, 0x35, 0x1a,
	0x10, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1a, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x76, 0x35, 0x2f, 0x65, 0x6e, 0x75, 0x6d,
	0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a,
	0x04, 0x55, 0x73, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x64, 0x6e,
	0x64, 0x6d, 0x6c, 0x2e, 0x76, 0x35, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x27, 0x0a, 0x08, 0x72,
	0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x52, 0x08, 0x72, 0x65, 0x63, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x61, 0x75, 0x66, 0x69, 0x73, 0x68, 0x2d, 0x67, 0x69, 0x74,
	0x2f, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x6e, 0x64, 0x6d, 0x6c,
	0x2f, 0x76, 0x35, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dndml_v5_uses_proto_rawDescOnce sync.Once
	file_dndml_v5_uses_proto_rawDescData = file_dndml_v5_uses_proto_rawDesc
)

func file_dndml_v5_uses_proto_rawDescGZIP() []byte {
	file_dndml_v5_uses_proto_rawDescOnce.Do(func() {
		file_dndml_v5_uses_proto_rawDescData = protoimpl.X.CompressGZIP(file_dndml_v5_uses_proto_rawDescData)
	})
	return file_dndml_v5_uses_proto_rawDescData
}

var file_dndml_v5_uses_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dndml_v5_uses_proto_goTypes = []interface{}{
	(*Uses)(nil),       // 0: dndml.v5.Uses
	(enums.Period)(0),  // 1: dndml.v5.enums.Period
	(*dndml.Roll)(nil), // 2: dndml.Roll
}
var file_dndml_v5_uses_proto_depIdxs = []int32{
	1, // 0: dndml.v5.Uses.period:type_name -> dndml.v5.enums.Period
	2, // 1: dndml.v5.Uses.recharge:type_name -> dndml.Roll
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dndml_v5_uses_proto_init() }
func file_dndml_v5_uses_proto_init() {
	if File_dndml_v5_uses_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dndml_v5_uses_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dndml_v5_uses_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dndml_v5_uses_proto_goTypes,
		DependencyIndexes: file_dndml_v5_uses_proto_depIdxs,
		MessageInfos:      file_dndml_v5_uses_proto_msgTypes,
	}.Build()
	File_dndml_v5_uses_proto = out.File
	file_dndml_v5_uses_proto_rawDesc = nil
	file_dndml_v5_uses_proto_goTypes = nil
	file_dndml_v5_uses_proto_depIdxs = nil
}
