# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dndml/v5/uses.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dndml import roll_pb2 as dndml_dot_roll__pb2
from dndml.v5.enums import enums_pb2 as dndml_dot_v5_dot_enums_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64ndml/v5/uses.proto\x12\x08\x64ndml.v5\x1a\x10\x64ndml/roll.proto\x1a\x1a\x64ndml/v5/enums/enums.proto\"\\\n\x04Uses\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12&\n\x06period\x18\x02 \x01(\x0e\x32\x16.dndml.v5.enums.Period\x12\x1d\n\x08recharge\x18\x03 \x01(\x0b\x32\x0b.dndml.RollB-Z+github.com/theaufish-git/dndml/pkg/dndml/v5b\x06proto3')



_USES = DESCRIPTOR.message_types_by_name['Uses']
Uses = _reflection.GeneratedProtocolMessageType('Uses', (_message.Message,), {
  'DESCRIPTOR' : _USES,
  '__module__' : 'dndml.v5.uses_pb2'
  # @@protoc_insertion_point(class_scope:dndml.v5.Uses)
  })
_sym_db.RegisterMessage(Uses)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/theaufish-git/dndml/pkg/dndml/v5'
  _USES._serialized_start=79
  _USES._serialized_end=171
# @@protoc_insertion_point(module_scope)
