# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dndml/obj.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dndml.enums import enums_pb2 as dndml_dot_enums_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64ndml/obj.proto\x12\x05\x64ndml\x1a\x17\x64ndml/enums/enums.proto\"\\\n\x06Object\x12!\n\x04kind\x18\x01 \x01(\x0e\x32\x13.dndml.enums.Object\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x13\n\x06source\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_sourceB*Z(github.com/theaufish-git/dndml/pkg/dndmlb\x06proto3')



_OBJECT = DESCRIPTOR.message_types_by_name['Object']
Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT,
  '__module__' : 'dndml.obj_pb2'
  # @@protoc_insertion_point(class_scope:dndml.Object)
  })
_sym_db.RegisterMessage(Object)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(github.com/theaufish-git/dndml/pkg/dndml'
  _OBJECT._serialized_start=51
  _OBJECT._serialized_end=143
# @@protoc_insertion_point(module_scope)
