// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: dndml/roll.proto

package dndml

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Roll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dice   uint32    `protobuf:"varint,1,opt,name=dice,proto3" json:"dice,omitempty"`
	Die    uint32    `protobuf:"varint,2,opt,name=die,proto3" json:"die,omitempty"`
	Reroll []*Reroll `protobuf:"bytes,3,rep,name=reroll,proto3" json:"reroll,omitempty"`
	Keep   *Keep     `protobuf:"bytes,4,opt,name=keep,proto3" json:"keep,omitempty"`
	Bonus  uint32    `protobuf:"varint,5,opt,name=bonus,proto3" json:"bonus,omitempty"`
}

func (x *Roll) Reset() {
	*x = Roll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dndml_roll_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Roll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Roll) ProtoMessage() {}

func (x *Roll) ProtoReflect() protoreflect.Message {
	mi := &file_dndml_roll_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Roll.ProtoReflect.Descriptor instead.
func (*Roll) Descriptor() ([]byte, []int) {
	return file_dndml_roll_proto_rawDescGZIP(), []int{0}
}

func (x *Roll) GetDice() uint32 {
	if x != nil {
		return x.Dice
	}
	return 0
}

func (x *Roll) GetDie() uint32 {
	if x != nil {
		return x.Die
	}
	return 0
}

func (x *Roll) GetReroll() []*Reroll {
	if x != nil {
		return x.Reroll
	}
	return nil
}

func (x *Roll) GetKeep() *Keep {
	if x != nil {
		return x.Keep
	}
	return nil
}

func (x *Roll) GetBonus() uint32 {
	if x != nil {
		return x.Bonus
	}
	return 0
}

type Keep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count  uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Lowest bool   `protobuf:"varint,2,opt,name=lowest,proto3" json:"lowest,omitempty"`
}

func (x *Keep) Reset() {
	*x = Keep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dndml_roll_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keep) ProtoMessage() {}

func (x *Keep) ProtoReflect() protoreflect.Message {
	mi := &file_dndml_roll_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keep.ProtoReflect.Descriptor instead.
func (*Keep) Descriptor() ([]byte, []int) {
	return file_dndml_roll_proto_rawDescGZIP(), []int{1}
}

func (x *Keep) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Keep) GetLowest() bool {
	if x != nil {
		return x.Lowest
	}
	return false
}

type Reroll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Die  uint32 `protobuf:"varint,1,opt,name=die,proto3" json:"die,omitempty"`
	Once bool   `protobuf:"varint,2,opt,name=once,proto3" json:"once,omitempty"`
}

func (x *Reroll) Reset() {
	*x = Reroll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dndml_roll_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reroll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reroll) ProtoMessage() {}

func (x *Reroll) ProtoReflect() protoreflect.Message {
	mi := &file_dndml_roll_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reroll.ProtoReflect.Descriptor instead.
func (*Reroll) Descriptor() ([]byte, []int) {
	return file_dndml_roll_proto_rawDescGZIP(), []int{2}
}

func (x *Reroll) GetDie() uint32 {
	if x != nil {
		return x.Die
	}
	return 0
}

func (x *Reroll) GetOnce() bool {
	if x != nil {
		return x.Once
	}
	return false
}

var File_dndml_roll_proto protoreflect.FileDescriptor

var file_dndml_roll_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x22, 0x8a, 0x01, 0x0a, 0x04, 0x52, 0x6f,
	0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x64, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x69, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x72, 0x6f,
	0x6c, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x6e, 0x64, 0x6d, 0x6c,
	0x2e, 0x52, 0x65, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x06, 0x72, 0x65, 0x72, 0x6f, 0x6c, 0x6c, 0x12,
	0x1f, 0x0a, 0x04, 0x6b, 0x65, 0x65, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x52, 0x04, 0x6b, 0x65, 0x65, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x22, 0x34, 0x0a, 0x04, 0x4b, 0x65, 0x65, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x77, 0x65, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x77, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x06,
	0x52, 0x65, 0x72, 0x6f, 0x6c, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x69, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x6e, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6f, 0x6e, 0x63, 0x65, 0x42, 0x2a, 0x5a, 0x28,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x61, 0x75,
	0x66, 0x69, 0x73, 0x68, 0x2d, 0x67, 0x69, 0x74, 0x2f, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dndml_roll_proto_rawDescOnce sync.Once
	file_dndml_roll_proto_rawDescData = file_dndml_roll_proto_rawDesc
)

func file_dndml_roll_proto_rawDescGZIP() []byte {
	file_dndml_roll_proto_rawDescOnce.Do(func() {
		file_dndml_roll_proto_rawDescData = protoimpl.X.CompressGZIP(file_dndml_roll_proto_rawDescData)
	})
	return file_dndml_roll_proto_rawDescData
}

var file_dndml_roll_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dndml_roll_proto_goTypes = []interface{}{
	(*Roll)(nil),   // 0: dndml.Roll
	(*Keep)(nil),   // 1: dndml.Keep
	(*Reroll)(nil), // 2: dndml.Reroll
}
var file_dndml_roll_proto_depIdxs = []int32{
	2, // 0: dndml.Roll.reroll:type_name -> dndml.Reroll
	1, // 1: dndml.Roll.keep:type_name -> dndml.Keep
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dndml_roll_proto_init() }
func file_dndml_roll_proto_init() {
	if File_dndml_roll_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dndml_roll_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Roll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dndml_roll_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Keep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dndml_roll_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reroll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dndml_roll_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dndml_roll_proto_goTypes,
		DependencyIndexes: file_dndml_roll_proto_depIdxs,
		MessageInfos:      file_dndml_roll_proto_msgTypes,
	}.Build()
	File_dndml_roll_proto = out.File
	file_dndml_roll_proto_rawDesc = nil
	file_dndml_roll_proto_goTypes = nil
	file_dndml_roll_proto_depIdxs = nil
}
