# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dndml/uses.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dndml import roll_pb2 as dndml_dot_roll__pb2
from dndml.enums import enums_pb2 as dndml_dot_enums_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ndml/uses.proto\x12\x05\x64ndml\x1a\x10\x64ndml/roll.proto\x1a\x17\x64ndml/enums/enums.proto\"Y\n\x04Uses\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12#\n\x06period\x18\x02 \x01(\x0e\x32\x13.dndml.enums.Period\x12\x1d\n\x08recharge\x18\x03 \x01(\x0b\x32\x0b.dndml.RollB*Z(github.com/theaufish-git/dndml/pkg/dndmlb\x06proto3')



_USES = DESCRIPTOR.message_types_by_name['Uses']
Uses = _reflection.GeneratedProtocolMessageType('Uses', (_message.Message,), {
  'DESCRIPTOR' : _USES,
  '__module__' : 'dndml.uses_pb2'
  # @@protoc_insertion_point(class_scope:dndml.Uses)
  })
_sym_db.RegisterMessage(Uses)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(github.com/theaufish-git/dndml/pkg/dndml'
  _USES._serialized_start=70
  _USES._serialized_end=159
# @@protoc_insertion_point(module_scope)
