// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: dndml/v5/enums/enums.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Class int32

const (
	Class_undefined_class Class = 0
	Class_barbarian       Class = 1
	Class_bard            Class = 2
	Class_cleric          Class = 3
	Class_fighter         Class = 4
	Class_monk            Class = 5
	Class_paladin         Class = 6
	Class_ranger          Class = 7
	Class_sorcerer        Class = 8
	Class_warlock         Class = 9
	Class_wizard          Class = 10
)

// Enum value maps for Class.
var (
	Class_name = map[int32]string{
		0:  "undefined_class",
		1:  "barbarian",
		2:  "bard",
		3:  "cleric",
		4:  "fighter",
		5:  "monk",
		6:  "paladin",
		7:  "ranger",
		8:  "sorcerer",
		9:  "warlock",
		10: "wizard",
	}
	Class_value = map[string]int32{
		"undefined_class": 0,
		"barbarian":       1,
		"bard":            2,
		"cleric":          3,
		"fighter":         4,
		"monk":            5,
		"paladin":         6,
		"ranger":          7,
		"sorcerer":        8,
		"warlock":         9,
		"wizard":          10,
	}
)

func (x Class) Enum() *Class {
	p := new(Class)
	*p = x
	return p
}

func (x Class) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Class) Descriptor() protoreflect.EnumDescriptor {
	return file_dndml_v5_enums_enums_proto_enumTypes[0].Descriptor()
}

func (Class) Type() protoreflect.EnumType {
	return &file_dndml_v5_enums_enums_proto_enumTypes[0]
}

func (x Class) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Class.Descriptor instead.
func (Class) EnumDescriptor() ([]byte, []int) {
	return file_dndml_v5_enums_enums_proto_rawDescGZIP(), []int{0}
}

type Period int32

const (
	Period_undefined_period Period = 0
	Period_round            Period = 1
	Period_short_rest       Period = 2
	Period_long_rest        Period = 3
	Period_day              Period = 4
)

// Enum value maps for Period.
var (
	Period_name = map[int32]string{
		0: "undefined_period",
		1: "round",
		2: "short_rest",
		3: "long_rest",
		4: "day",
	}
	Period_value = map[string]int32{
		"undefined_period": 0,
		"round":            1,
		"short_rest":       2,
		"long_rest":        3,
		"day":              4,
	}
)

func (x Period) Enum() *Period {
	p := new(Period)
	*p = x
	return p
}

func (x Period) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Period) Descriptor() protoreflect.EnumDescriptor {
	return file_dndml_v5_enums_enums_proto_enumTypes[1].Descriptor()
}

func (Period) Type() protoreflect.EnumType {
	return &file_dndml_v5_enums_enums_proto_enumTypes[1]
}

func (x Period) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Period.Descriptor instead.
func (Period) EnumDescriptor() ([]byte, []int) {
	return file_dndml_v5_enums_enums_proto_rawDescGZIP(), []int{1}
}

var File_dndml_v5_enums_enums_proto protoreflect.FileDescriptor

var file_dndml_v5_enums_enums_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x76, 0x35, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73,
	0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x64, 0x6e,
	0x64, 0x6d, 0x6c, 0x2e, 0x76, 0x35, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2a, 0x98, 0x01, 0x0a,
	0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x13, 0x0a, 0x0f, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x65, 0x64, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x62,
	0x61, 0x72, 0x62, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x62, 0x61,
	0x72, 0x64, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x63, 0x6c, 0x65, 0x72, 0x69, 0x63, 0x10, 0x03,
	0x12, 0x0b, 0x0a, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x65, 0x72, 0x10, 0x04, 0x12, 0x08, 0x0a,
	0x04, 0x6d, 0x6f, 0x6e, 0x6b, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x70, 0x61, 0x6c, 0x61, 0x64,
	0x69, 0x6e, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x10, 0x07,
	0x12, 0x0c, 0x0a, 0x08, 0x73, 0x6f, 0x72, 0x63, 0x65, 0x72, 0x65, 0x72, 0x10, 0x08, 0x12, 0x0b,
	0x0a, 0x07, 0x77, 0x61, 0x72, 0x6c, 0x6f, 0x63, 0x6b, 0x10, 0x09, 0x12, 0x0a, 0x0a, 0x06, 0x77,
	0x69, 0x7a, 0x61, 0x72, 0x64, 0x10, 0x0a, 0x2a, 0x51, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x12, 0x14, 0x0a, 0x10, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x5f, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x74,
	0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x10,
	0x03, 0x12, 0x07, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x10, 0x04, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x61, 0x75, 0x66, 0x69,
	0x73, 0x68, 0x2d, 0x67, 0x69, 0x74, 0x2f, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x64, 0x6e, 0x64, 0x6d, 0x6c, 0x2f, 0x76, 0x35, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dndml_v5_enums_enums_proto_rawDescOnce sync.Once
	file_dndml_v5_enums_enums_proto_rawDescData = file_dndml_v5_enums_enums_proto_rawDesc
)

func file_dndml_v5_enums_enums_proto_rawDescGZIP() []byte {
	file_dndml_v5_enums_enums_proto_rawDescOnce.Do(func() {
		file_dndml_v5_enums_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_dndml_v5_enums_enums_proto_rawDescData)
	})
	return file_dndml_v5_enums_enums_proto_rawDescData
}

var file_dndml_v5_enums_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dndml_v5_enums_enums_proto_goTypes = []interface{}{
	(Class)(0),  // 0: dndml.v5.enums.Class
	(Period)(0), // 1: dndml.v5.enums.Period
}
var file_dndml_v5_enums_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dndml_v5_enums_enums_proto_init() }
func file_dndml_v5_enums_enums_proto_init() {
	if File_dndml_v5_enums_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dndml_v5_enums_enums_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dndml_v5_enums_enums_proto_goTypes,
		DependencyIndexes: file_dndml_v5_enums_enums_proto_depIdxs,
		EnumInfos:         file_dndml_v5_enums_enums_proto_enumTypes,
	}.Build()
	File_dndml_v5_enums_enums_proto = out.File
	file_dndml_v5_enums_enums_proto_rawDesc = nil
	file_dndml_v5_enums_enums_proto_goTypes = nil
	file_dndml_v5_enums_enums_proto_depIdxs = nil
}
